import { randomBytes } from 'node:crypto';
import type { IncomingMessage, ServerResponse } from 'node:http';

// Trusted owner code only. Authored markup is sanitized in a detached document,
// serialized into opaque sandboxed srcdoc, and never inserted in the owner DOM.
export const ownerScript = String.raw`
const root=document.querySelector('main'),status=document.querySelector('#status');
const say=(s)=>{status.textContent=s;};
const el=(tag,text,parent=root)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;parent.append(n);return n;};
const button=(text,fn,parent=root)=>{const b=el('button',text,parent);b.type='button';b.addEventListener('click',()=>busy(fn));return b;};
const field=(label,type,parent)=>{const l=el('label',label,parent),i=el(type==='textarea'?'textarea':'input',undefined,l);if(type!=='textarea')i.type=type;i.required=true;i.maxLength=2048;return i;};
async function api(path,data){const r=await fetch(path,{method:data===undefined?'GET':'POST',credentials:'same-origin',headers:data===undefined?{}:{'content-type':'application/json'},body:data===undefined?undefined:JSON.stringify(data),cache:'no-store'});const v=await r.json();if(!r.ok){if(v.code==='AUTH_REQUIRED'){root.replaceChildren();secretForm('claim');}throw Error(v.code||'REQUEST_FAILED');}return v;}
let operationContract;
async function contract(){
 if(!operationContract)operationContract=Promise.all([api('/api/operations/contract'),api('/mcp/manifest.json')]).then(([owner,manifest])=>{
  if(owner.schemaVersion!==manifest.toolContractVersion||JSON.stringify(owner.readTools)!==JSON.stringify(manifest.capabilities.readTools)||JSON.stringify(owner.tools.filter(t=>manifest.capabilities.tools.includes(t.name)))!==JSON.stringify(manifest.capabilities.toolSchemas))throw Error('CONTRACT_MISMATCH');
  return owner;
 }).catch(error=>{operationContract=null;throw error;});
 return operationContract;
}
async function op(name,args={}){
 const spec=await contract(),tool=spec.tools.find(t=>t.name===name),schema=tool?.inputSchema;
 if(!schema||Object.keys(args).some(key=>!Object.hasOwn(schema.properties,key))||schema.required.some(key=>args[key]===undefined))throw Error('CONTRACT_MISMATCH');
 const result=await api('/api/operations',{name,arguments:args});
 if(result.code==='REFRESH_CONFLICT')return result;
 const isRead=spec.readTools.includes(name),required=isRead?spec.readResponseRequired:spec.receiptRequired;
 if((!isRead&&result.operation!==name)||!required.every(key=>Object.hasOwn(result,key)))throw Error('CONTRACT_MISMATCH');
 return result;
}
const messages={AUTH_REQUIRED:'Owner access is required. Use the browser where you claimed this Foldy.',OWNER_REQUIRED:'Owner access is required.',SEALED:'This Foldy is sealed. Claim it with your one-use owner key.',ALREADY_CLAIMED:'This Foldy has already been claimed. Use the original owner browser; the one-use key cannot sign you in again.',AUTH_INVALID:'The key or password was not accepted. Check it and try again.',REVISION_CONFLICT:'This update has changed. Refresh and review the latest version before deciding.',APPROVAL_STALE:'Approval is out of date. Refresh and review again.',BLOCKING_COMMENTS:'Resolve blocking comments before approval or publication.',CACHE_UNAVAILABLE:'Access could not be changed safely. Viewing is locked; contact your operator.',RATE_LIMITED:'Too many attempts. Wait a minute before trying again.'};
let working=false;
async function busy(fn){if(working)return;working=true;root.setAttribute('aria-busy','true');root.querySelectorAll('button').forEach(b=>b.disabled=true);say('Working…');try{await fn();}catch(e){say(messages[e.message]||'Could not complete this request. Refresh to check the current state before trying again.');}finally{working=false;root.removeAttribute('aria-busy');root.querySelectorAll('button').forEach(b=>b.disabled=false);}}
function form(parent,submit){const f=el('form',undefined,parent);f.addEventListener('submit',e=>{e.preventDefault();busy(()=>submit(f));});return f;}
function submit(text,f){const b=el('button',text,f);b.type='submit';return b;}
async function downloadBackup(){const r=await fetch('/api/backup',{method:'GET',credentials:'same-origin',cache:'no-store'});if(!r.ok)throw Error('BACKUP_FAILED');const blob=await r.blob(),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='foldy-backup.json';a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);await dashboard();say('Backup download started. Keep it private: it contains your Foldy content and review history, not sign-in credentials.');}
function ownerLogout(parent=root){button('Log out of owner workspace',async()=>{await api('/api/owner/logout',{});secretForm('claim');say('Owner access has been signed out. An operator-authorized recovery key is needed to regain access.');},parent);}
function ownerRecovery(){el('h2','Recover owner access');el('p','Ask your deploying operator to authorize recovery and supply a one-use recovery key. The original claim key and viewing password cannot recover ownership. Recovery revokes existing owner and MCP access.');const f=form(root,async()=>{const assertion=i.value;i.value='';await api('/api/owner/recover',{assertion});await start();say('Owner access recovered. Previous owner and MCP access has been revoked.');});const i=field('One-use recovery key','password',f);i.autocomplete='off';i.minLength=32;i.maxLength=256;submit('Recover owner access',f);}
function secretForm(kind){root.replaceChildren();el('h1',kind==='claim'?'Claim your Foldy':'Open this Foldy');el('p',kind==='claim'?'Enter the one-use owner key supplied by your operator. It stays out of links and browser storage. Already claimed? Return to your original owner browser.':'Enter the viewing password. Viewing access does not grant owner access.');const f=form(root,async()=>{const password=i.value;i.value='';await api(kind==='claim'?'/api/claim':'/api/viewer/unlock',kind==='claim'?{assertion:password}:{password});if(kind==='claim')await start();else{say('Unlocked. Opening your Foldy…');location.assign('/');}});const i=field(kind==='claim'?'One-use owner key':'Viewing password','password',f);i.autocomplete='off';i.maxLength=kind==='claim'?256:1024;submit(kind==='claim'?'Claim ownership':'Unlock',f);button('Check access again',start);if(kind==='claim')ownerRecovery();}
async function start(){say('Checking access…');if(location.pathname==='/unlock'){const s=await api('/api/viewer-access');if(s.mode==='public'){root.replaceChildren();el('h1','This Foldy is public');const a=el('a','Open Foldy');a.href='/';say('No password needed.');}else{secretForm('unlock');say(s.mode==='unavailable'?'Viewing is temporarily unavailable. Contact the owner.':'Password required.');}button('Log out of viewing',async()=>{await api('/api/viewer/logout',{});await start();say('Viewing session signed out. Public content, if enabled by the owner, remains readable.');});return;}try{const readiness=await api('/api/readiness');if(readiness.state==='ACCESS_CONFIGURATION_REQUIRED'){await recoveryAccess();return;}await dashboard();}catch(e){if(e.message==='ACCESS_CONFIGURATION_REQUIRED'){await recoveryAccess();return;}if(e.message==='AUTH_REQUIRED'||e.message==='SEALED'){secretForm('claim');say('Owner access is not active in this browser.');}else throw e;}}
async function dashboard(){const [r,updates,access]=await Promise.all([api('/api/readiness'),op('list_updates'),api('/api/owner/viewer-access')]);root.replaceChildren();el('p','OWNER WORKSPACE',root).className='eyebrow';el('h1','Review what’s next');el('p','Review proposed changes, leave feedback and choose what your readers see.');const toolbar=el('div');toolbar.className='actions';button('Refresh',dashboard,toolbar);button('Download backup',downloadBackup,toolbar);ownerLogout(toolbar);const a=el('a','Open published Foldy',toolbar);a.href='/';el('p','Storage: '+r.storage+' · Content: '+r.bundle+' · Owner access active');const layout=el('div');layout.className='workspace';const list=el('section',undefined,layout);el('h2','Updates',list);if(!updates.value.length)el('p','No updates yet. New proposals will appear here when they are submitted.',list);for(const u of updates.value){const row=el('article',undefined,list);el('h3',u.title,row);el('p',u.state,row);button('Review update',()=>review(u.id),row);}const settings=el('section',undefined,layout);el('h2','Reader access',settings);el('p',access.mode==='public'?'Anyone with the address can read this Foldy.':access.mode==='password_required'?'Readers need a password. Owner access is separate.':'Viewing is unavailable until access is repaired.',settings);const f=form(settings,async()=>{if(!confirm('Set a viewing password? Existing viewer sessions will be signed out.'))return;const password=p.value;p.value='';await api('/api/owner/viewer-access',{mode:'password_required',password});await dashboard();say('Viewing password saved. Previous viewer sessions no longer have access.');});const p=field('New viewing password','password',f);p.autocomplete='new-password';p.maxLength=1024;submit('Require password',f);button('Allow public reading',async()=>{if(!confirm('Allow anyone with this address to read all published content without a password?'))return;await api('/api/owner/viewer-access',{mode:'public',confirmDisable:true});await dashboard();say('Public reading is enabled.');},settings);await ownerStatus();await connectAssistants();say('Up to date.');}
async function ownerStatus(){
 const report=await api('/api/owner/status'),section=el('section');el('h2','Instance status',section);
 const rows=[['Runtime',report.runtimeVersion],['Image',report.runtimeImageDigest],['Instance',report.instanceId],['Published revision',report.currentPublishedRevisionId],['Storage',report.storage],['Reader access',report.browserAccessMode],['Hosting lease','Not verified by this runtime']];
 const facts=el('dl',undefined,section);for(const [label,value]of rows){el('dt',label,facts);el('dd',value,facts);}
 const backup=report.operations.lastBackup;el('p',backup?'Last backup prepared: '+backup.createdAt+' · Revision '+backup.revisionId:'No backup has been prepared by this runtime.',section);el('p','Backup preparation does not confirm that the download was saved or that restoration has been tested.',section);
 const failure=report.operations.latestFailure;if(failure)el('p','Latest failed owner operation: '+failure.operation+' · '+failure.occurredAt+' · Reference '+failure.requestId,section);
 button('Download diagnostics',async()=>{const data=await api('/api/owner/diagnostics'),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=el('a');a.href=url;a.download='foldy-diagnostics.json';a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);say('Diagnostics downloaded. This report excludes content and sign-in credentials.');},section);
}
async function connectAssistants(){
 const [m,list]=await Promise.all([api('/mcp/manifest.json'),api('/api/mcp-grants')]);
 const section=el('section');el('h2','Connect assistants',section);
 const endpoint=new URL(m.endpoint,location.origin),discovery=new URL(m.authenticationDiscovery.protectedResourceMetadata,location.origin);
 if(endpoint.origin!==location.origin||discovery.origin!==location.origin)throw Error('REQUEST_FAILED');
 el('p','Instance '+m.instanceId+' · '+m.transport,section);el('p','MCP endpoint: '+endpoint.href,section);
 const link=el('a','OAuth discovery (preferred)',section);link.href=discovery.href;
 el('p','Start the connection in your assistant, then open its authorization link in this owner browser. Review the requested scopes before allowing access. No owner, approval, publication, access administration or backup permissions are granted.',section);
 for(const [name,instruction]of [['ChatGPT','Use a custom remote MCP connector where your account supports it. Supply the endpoint and follow its OAuth authorization link. Cloud connectors require reachable HTTPS; loopback is not reachable.'],['Claude Desktop','Use a remote custom connector where your version and account support it. Supply the endpoint and complete OAuth. A stdio-only configuration cannot directly consume this HTTP endpoint.'],['Claude Code','Add a remote HTTP MCP server using your installed version’s MCP configuration, with the endpoint below, then use its authentication flow.'],['Generic MCP client','Use Streamable HTTP with protected-resource discovery, dynamic client registration and authorization-code PKCE S256. Request foldy:read by default.']]){el('h3',name,section);el('p',instruction,section);el('code',endpoint.href,section);}
 el('p','These are connection instructions, not verified account integrations. Named clients, account plans, versions and network reachability have not been tested here. No refresh tokens are supported; reconnect after expiry.',section);
 const label=el('label','Explicitly allow draft proposals (never approval or publication)',section),draft=el('input',undefined,label);draft.type='checkbox';draft.checked=false;draft.disabled=!m.capabilities.scopes.includes('foldy:draft:write');
 const scopeText=el('p','Requested scope: foldy:read',section);draft.addEventListener('change',()=>scopeText.textContent='Request these scopes in the client: foldy:read'+(draft.checked?' foldy:draft:write':''));
 const fallback=el('details',undefined,section);el('summary','Advanced: one-time opaque token custody',fallback);el('p','Only for clients supporting a protected Authorization header. Prefer OAuth. Never place a credential in a URL, browser storage, shell history or logs. It is shown once here; keep it in your client’s protected credential store, then dismiss it.',fallback);
 button('Issue and reveal one-time token',async()=>{if(!confirm('Issue a secret and show it once in this owner browser?'))return;const result=await api('/api/mcp-grants',{scopes:draft.checked?['foldy:read','foldy:draft:write']:['foldy:read']});const box=el('div',undefined,fallback);el('p','Store securely now; this token cannot be retrieved again.',box);el('pre',result.token,box);result.token='';button('Dismiss secret and refresh grants',async()=>{box.replaceChildren();await dashboard();},box);setTimeout(()=>box.replaceChildren(),60000);},fallback);
 el('h3','Assistant grants',section);if(!list.grants.length)el('p','No assistant grants.',section);
 for(const grant of list.grants){const row=el('article',undefined,section);el('p',grant.kind+' · '+grant.grantId,row);el('p',grant.scopes.join(', ')+' · expires '+new Date(grant.expiresAt).toISOString()+(grant.active?'':' · expired'),row);button('Revoke this grant',async()=>{if(!confirm('Revoke this assistant grant and terminate its sessions?'))return;await api('/api/mcp-grants/revoke',{grantId:grant.grantId});await dashboard();say('Grant revoked.');},row);}
 button('Revoke all assistant grants',async()=>{if(!confirm('Revoke every assistant grant and terminate all MCP sessions?'))return;await api('/api/mcp-grants/revoke-all',{});await dashboard();say('All assistant grants revoked.');},section);
}
async function recoveryAccess(){await api('/api/owner/viewer-access');root.replaceChildren();el('h1','Choose reader access');ownerLogout();button('Download backup',downloadBackup);el('p','This restored Foldy remains locked. Claiming ownership does not open its content. Choose how readers may access it before continuing.');const f=form(root,async()=>{const password=p.value;p.value='';await api('/api/owner/viewer-access',{mode:'password_required',password});await start();});const p=field('New viewing password','password',f);p.autocomplete='new-password';p.maxLength=1024;submit('Require password and continue',f);button('Enable public reading',async()=>{if(!confirm('Open restored content to anyone with the address, without a password?'))return;await api('/api/owner/viewer-access',{mode:'public',confirmDisable:true});await start();});say('Reader access must be configured before this Foldy can open.');}
const decode=f=>f?new TextDecoder().decode(Uint8Array.from(atob(f.content),c=>c.charCodeAt(0))):'No previous content';
// Parsing stays in a detached, inert document; authored nodes never enter the owner DOM.
const previewNonce=document.querySelector('script[nonce]').nonce;
function previewHtml(file,files,path){
 const doc=new DOMParser().parseFromString(decode(file),'text/html');
 const assetPath=(url,from=path)=>{try{const base=new URL(from,'https://preview.invalid/'),u=new URL(url,base);return u.origin==='https://preview.invalid'&&!u.search?decodeURIComponent(u.pathname.slice(1)):null;}catch{return null;}};
 const image=(url,from=path)=>{const f=files[assetPath(url,from)];return f&&/^image\/(png|jpeg|gif|webp)$/.test(f.mediaType)?'data:'+f.mediaType+';base64,'+f.content:'';};
 const cssText=(text,from)=>text.replace(/url\(\s*(['"]?)(.*?)\1\s*\)/gi,(_,q,url)=>'url("'+image(url,from)+'")').replace(/@import\b[^;]*(;|$)/gi,'');
 const styles=[];
 for(const node of [...doc.querySelectorAll('*')]){
  const tag=node.localName;
  if(tag==='style'){styles.push(cssText(node.textContent,path));node.remove();continue;}
  if(tag==='link'){const key=assetPath(node.getAttribute('href')||'');const f=files[key];if(node.getAttribute('rel')==='stylesheet'&&f?.mediaType==='text/css')styles.push(cssText(decode(f),key));node.remove();continue;}
  if(!/^(html|head|body|title|div|span|p|h[1-6]|section|article|main|header|footer|nav|aside|ul|ol|li|dl|dt|dd|table|thead|tbody|tfoot|tr|td|th|caption|colgroup|col|strong|em|b|i|u|s|small|br|hr|pre|code|blockquote|figure|figcaption|img|a|form|label|input|button|textarea|select|option|details|summary)$/.test(tag)){node.remove();continue;}
  const imageSource=tag==='img'?image(node.getAttribute('src')||''):'';
  for(const a of [...node.attributes]){
   if(a.name==='style'){const key='s'+styles.length;styles.push('[data-preview-style="'+key+'"]{'+cssText(a.value,path)+'}');node.setAttribute('data-preview-style',key);}
   if(!/^(class|id|title|alt|width|height|colspan|rowspan|lang|dir)$/.test(a.name))node.removeAttribute(a.name);
  }
  if(imageSource)node.setAttribute('src',imageSource);
  if(['input','button','textarea','select'].includes(tag))node.setAttribute('disabled','');
 }
 const policy="default-src 'none'; script-src 'none'; style-src 'nonce-"+previewNonce+"'; img-src data:; connect-src 'none'; frame-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'";
 const meta=doc.createElement('meta');meta.httpEquiv='Content-Security-Policy';meta.content=policy;doc.head.prepend(meta);
 const style=doc.createElement('style');style.setAttribute('nonce',previewNonce);style.textContent='html{overflow-wrap:anywhere}body{margin:16px;font:16px/1.5 system-ui}img{max-width:100%;height:auto}*{box-sizing:border-box}'+styles.join('\n').replaceAll('<','\\3c ');doc.head.append(style);
 return '<!doctype html>'+doc.documentElement.outerHTML;
}
async function revisionFiles(revision){const listing=await op('list_files',{atRevisionId:revision});const entries=await Promise.all(listing.value.map(async f=>{const r=await op('get_file',{atRevisionId:revision,path:f.path});if(r.observedRevisionId!==revision)throw Error('REVISION_CONFLICT');return [f.path,{content:r.value.bytes,mediaType:r.value.mediaType}];}));return Object.fromEntries(entries);}
function readableContent(file){
 if(file?.mediaType!=='text/html')return {headings:[],text:[]};
 const doc=new DOMParser().parseFromString(decode(file),'text/html');
 doc.querySelectorAll('script,style,template,noscript,iframe,svg').forEach(node=>node.remove());
 const lines=selector=>[...doc.querySelectorAll(selector)].map(node=>node.textContent.replace(/\s+/g,' ').trim()).filter(Boolean);
 return {headings:lines('h1,h2,h3'),text:lines('p,li')};
}
function changeSummary(changes){
 const summary=el('section');summary.setAttribute('role','region');summary.setAttribute('aria-label','Change summary');
 el('h2','Change summary',summary);
 el('p','A quick view of changed pages and words. Compare the isolated previews and source below for the full version.',summary);
 if(!changes.length){el('p','No pages or files changed.',summary);return;}
 const list=el('ul',undefined,summary);
 const excerpt=text=>text.length>140?text.slice(0,139).trimEnd()+'…':text;
 for(const change of changes){
  const item=el('li',undefined,list),kind=!change.before?'Added':!change.after?'Removed':'Edited';
  el('strong',kind+': '+change.path,item);
  if(change.before?.mediaType!=='text/html'&&change.after?.mediaType!=='text/html'){el('p','Source-only change; inspect the source below.',item);continue;}
  const before=readableContent(change.before),after=readableContent(change.after);
  for(const [label,key] of [['Heading','headings'],['Text','text']]){
   const old=before[key].filter(line=>!after[key].includes(line)).slice(0,2);
   const fresh=after[key].filter(line=>!before[key].includes(line)).slice(0,2);
   if(old.length||fresh.length)el('p',label+': '+(old.length?old.map(excerpt).join('; '):'none')+' → '+(fresh.length?fresh.map(excerpt).join('; '):'none'),item);
  }
  if(!item.querySelector('p'))el('p','Layout or other content changed; compare previews below.',item);
 }
}
async function review(id){const result=await op('get_update',{updateId:id}),u=result.value;const [changes,checks,preview,beforeFiles]=await Promise.all([op('get_update_changes',{updateId:id,atRevisionId:u.revision}),op('get_readiness_checks',{updateId:id,atRevisionId:u.revision}),op('get_update_preview',{updateId:id,atRevisionId:u.revision}),revisionFiles(u.base)]);if(preview.value.revisionId!==u.revision||preview.observedRevisionId!==u.revision)throw Error('REVISION_CONFLICT');root.replaceChildren();button('All updates',dashboard);el('h1',u.title);el('p',u.state);const c=checks.value;el('p',(c.baseCurrent?'Based on the current publication.':'Out of date: publication has changed.')+' '+c.blockingComments+' unresolved blocking comments. '+(c.approved?'This version is approved.':'This version is not approved.'));changeSummary(changes.value);el('h2','Changes');el('p','Static, isolated previews of this exact version. Scripts, forms, links and external content are disabled; full app interactivity is not guaranteed. Expand source for content that cannot be rendered.');if(!changes.value.length)el('p','There are no content changes in this update.');for(const change of changes.value){const section=el('section');el('h3',change.path,section);const pair=el('div',undefined,section);pair.className='comparison';for(const [label,value]of [['Before',change.before],['After',change.after]]){const panel=el('div',undefined,pair);el('h4',label,panel);if(value?.mediaType==='text/html'){const frame=el('iframe',undefined,panel);frame.title=label+': '+change.path;frame.setAttribute('sandbox','');frame.referrerPolicy='no-referrer';frame.srcdoc=previewHtml(value,label==='Before'?beforeFiles:preview.value.files,change.path);}else el('p',value?'Source-only change':'No content in this version',panel);const details=el('details',undefined,panel);el('summary','Show source',details);el('pre',decode(value),details);}}
const evidence=el('details');el('summary','Readiness evidence',evidence);el('p','Revision: '+c.revisionId+' · Entry present: '+c.entryPresent+' · Dependencies: '+(c.dependencies.pass?'Pass':'Failed'),evidence);el('p','Files digest: '+c.dependencies.filesDigest,evidence);for(const failure of c.dependencies.failures)el('p',failure.path+' · '+failure.reference+' · '+failure.reason,evidence);
const history=el('details');el('summary','Revision history',history);const revisions=await op('get_revision_history');for(const revision of revisions.value)el('p',revision.id+' · Parent: '+(revision.parent||'None')+' · Actor: '+revision.actor,history);
const decisions=el('details');el('summary','Decision history',decisions);if(!u.decisions?.length)el('p','No owner decisions recorded yet.',decisions);for(const decision of u.decisions||[]){const row=el('article',undefined,decisions);el('p',decision.currentState+' · '+decision.occurredAt,row);el('p',decision.reason||'No reason recorded',row);el('p','Revision '+decision.updateRevisionId+' · Reference '+decision.receiptId,row);}const conflicts=el('section');conflicts.hidden=true;conflicts.setAttribute('role','alert');
const mutate=async(name,extra={})=>{const refreshing=name==='refresh_update_proposal';const [project,fresh]=await Promise.all([op('get_project'),op('get_update',{updateId:id})]);if(fresh.value.base!==u.base||fresh.value.revision!==u.revision||fresh.value.state!==u.state||JSON.stringify(fresh.value.comments)!==JSON.stringify(u.comments)||(!refreshing&&name!=='close_update'&&project.observedRevisionId!==u.base))throw Error('REVISION_CONFLICT');const receipt=await op(name,{projectId:project.value.projectId,updateId:id,expectedBaseRevisionId:u.base,expectedUpdateRevisionId:u.revision,idempotencyKey:crypto.randomUUID(),...extra,...(refreshing?{newPublishedBaseRevisionId:project.observedRevisionId}:{})});if(receipt.code==='REFRESH_CONFLICT'){conflicts.replaceChildren();conflicts.hidden=false;el('h2','Refresh conflicts',conflicts);el('p','No changes were applied. Your proposal, comments and entered feedback are preserved. Ask the author to reconcile these paths before refreshing again.',conflicts);const paths=el('ul',undefined,conflicts);for(const conflict of receipt.conflicts)el('li',conflict.path,paths);el('p','Proposal revision: '+receipt.updateRevisionId+' · Published revision: '+receipt.currentPublishedRevisionId,conflicts);say('Refresh has conflicts. Nothing was changed.');return;}await review(id);say('Saved. Update is now '+receipt.currentState+'.'+(receipt.reason?' Reason: '+receipt.reason:''));};
if(!c.baseCurrent&&!['Closed','Published'].includes(u.state)){el('p','Refresh merges non-conflicting changes onto the latest publication, keeps review history and returns this proposal to Draft. Conflicts do not overwrite either version.');button('Refresh proposal',async()=>{if(confirm('Refresh this proposal onto the latest publication? Approval will need to be requested again.'))await mutate('refresh_update_proposal');});}
el('h2','Comments');if(!u.comments.length)el('p','No review comments yet.');for(const comment of u.comments){const article=el('article');el('p',comment.text,article);el('p',Object.entries(comment.target).map(([k,v])=>k+': '+v).join(' · ')||'Whole update',article);el('p',(comment.resolved?'Resolved':comment.blocking?'Blocking':'Open')+(comment.revision!==u.revision?' · Earlier version':''),article);if(!comment.resolved&&!['Closed','Published'].includes(u.state))button('Resolve comment',async()=>{const reason=prompt('What resolved this comment?');if(!reason?.trim())return;await mutate('resolve_review_comment',{commentId:comment.id,reason:reason.trim()});},article);}
if(!['Closed','Published'].includes(u.state)){const targets={};const cf=form(root,async()=>{await mutate('add_review_comment',{text:text.value.trim(),blocking:block.checked,target:Object.fromEntries(Object.entries(targets).filter(([,input])=>input.value.trim()).map(([key,input])=>[key,input.value.trim()]))});});el('h3','Add feedback',cf);const text=field('Comment','textarea',cf);for(const [key,label]of [['path','Page path'],['block','Block'],['field','Field'],['selection','Selection']]){targets[key]=field(label+' (optional)','text',cf);targets[key].required=false;}targets.path.placeholder='index.html';const blockLabel=el('label','This comment blocks approval',cf),block=el('input',undefined,blockLabel);block.type='checkbox';submit('Add comment',cf).className='secondary';}
if(['Draft','Changes requested'].includes(u.state)&&c.baseCurrent&&!c.blockingComments&&c.entryPresent&&c.dependencies.pass)button('Request review',async()=>{if(confirm('Submit this exact proposal version for review?'))await mutate('submit_update_for_review');});
const actions=el('section');el('h2','Your decision',actions);el('p','Decisions apply only to the version you have reviewed. Approval does not publish. Publish separately after approval. Publishing replaces the content readers currently see.',actions);const reason=field('Reason for your decision (required)','textarea',actions);const choices=[['Close update','close_update'],['Request changes','request_update_changes'],...(u.state==='Ready for review'&&!c.blockingComments&&c.baseCurrent?[['Approve this version','approve_update_revision']]:[]),...(u.state==='Approved'&&c.approved&&c.baseCurrent&&!c.blockingComments?[['Publish this version','publish_update']]:[])];if(!['Published','Closed'].includes(u.state))for(const [label,name]of choices)button(label,async()=>{if(!reason.value.trim()){reason.reportValidity();say('Add a reason for your decision.');return;}if(!confirm(label+' for “'+u.title+'”? '+(name==='publish_update'?'Readers will see this version immediately.':'This decision will be recorded.')))return;await mutate(name,{reason:reason.value.trim()});},actions).className=name==='approve_update_revision'||name==='publish_update'?'primary':'';say(c.baseCurrent?'Review loaded.':'This proposal is out of date. Refresh before review or publication, or close it without changing published content.');}
busy(start);
`;
const css = `:root{--bg:#faf9f7;--panel:#fff;--border:#c9d0da;--text:#1a1916;--muted:#615e58;--accent:#b45a3b}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:16px/1.55 -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}header{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid var(--border);padding:16px 32px;background:var(--panel)}main{padding:32px;width:100%;min-width:0}h1{font-size:clamp(28px,4vw,40px);line-height:1.2;margin:12px 0}h2{font-size:23px}h3{font-size:18px}p{overflow-wrap:anywhere}a{color:var(--accent);display:inline-flex;align-items:center;min-height:44px}button,input,textarea{font:inherit;min-height:44px;border:1px solid var(--border);border-radius:8px;padding:10px 14px}button{background:var(--panel);color:var(--text);cursor:pointer}button:hover{background:#eef1f5}button[type=submit]:not(.secondary),button.primary{background:var(--accent);color:white;border-color:var(--accent)}button:disabled{opacity:.55;cursor:wait}:focus-visible{outline:3px solid #2348b8;outline-offset:3px}label{display:grid;gap:6px}input,textarea{width:100%;background:white;color:var(--text)}input[type=checkbox]{width:44px}textarea{min-height:100px}form{display:grid;gap:16px;max-width:620px;margin:20px 0}section,article{min-width:0;border-top:1px solid var(--border);padding:20px 0}article button{margin-top:8px}.workspace{display:grid;grid-template-columns:minmax(0,2fr) minmax(0,1fr);gap:40px}.comparison{display:grid;grid-template-columns:1fr 1fr;gap:20px}.comparison>div{min-width:0}dd{margin:0 0 12px;overflow-wrap:anywhere}dt{font-weight:600}.comparison iframe{display:block;width:100%;height:360px;border:1px solid var(--border);background:white}.comparison summary{cursor:pointer;padding:12px 0}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#eef1f5;border:1px solid var(--border);padding:16px;max-height:420px;overflow:auto;font-size:14px}.actions{display:flex;flex-wrap:wrap;gap:16px}section>button{margin:12px 12px 0 0}.eyebrow{font-size:12px;letter-spacing:.12em;font-weight:700;color:var(--muted)}#status{padding:12px 32px;min-height:48px;border-bottom:1px solid var(--border);background:var(--panel)}@media(max-width:700px){header,main{padding:16px}#status{padding:12px 16px}.workspace,.comparison{grid-template-columns:1fr;gap:16px}button{max-width:100%}}`;
export function ownerUiRoute(req: IncomingMessage, res: ServerResponse, path: string): boolean {
 if (!['/owner','/unlock','/owner/app.js'].includes(path)) return false;
 if (req.method !== 'GET' && req.method !== 'HEAD') { res.writeHead(405); res.end(); return true; }
 res.setHeader('cache-control','no-store');
 if(path==='/owner/app.js'){res.setHeader('content-type','text/javascript; charset=utf-8');res.end(req.method==='HEAD'?undefined:ownerScript);return true;}
 const nonce=randomBytes(24).toString('base64');
 res.setHeader('content-security-policy',`default-src 'none'; script-src 'nonce-${nonce}'; style-src 'nonce-${nonce}'; connect-src 'self'; frame-src about:; img-src data:; base-uri 'none'; form-action 'none'; frame-ancestors 'none'`);
 res.setHeader('referrer-policy','no-referrer');
 res.setHeader('content-type','text/html; charset=utf-8');
 res.end(req.method==='HEAD'?undefined:`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${path==='/owner'?'Owner workspace':'Unlock'} · Foldy</title><style nonce="${nonce}">${css}</style></head><body><header><strong>Foldy</strong><a href="${path==='/owner'?'/unlock':'/owner'}">${path==='/owner'?'Reader access':'Owner workspace'}</a></header><div id="status" role="status" aria-live="polite">Loading…</div><main><h1>${path==='/owner'?'Owner workspace':'Open this Foldy'}</h1><noscript>JavaScript is required for secure access. No content is loaded until access is checked.</noscript></main><script nonce="${nonce}" src="/owner/app.js" defer></script></body></html>`);
 return true;
}
